# Common vars - for all platforms
unset TEST_AGENT_USER
unset TEST_CFY_MANAGER
unset TEST_CFY_MANAGER_USERNAME
unset TEST_CFY_MANAGER_PASSWORD
unset TEST_SUPERUSER_USERNAME
unset TEST_SUPERUSER_PASSWORD
unset TEST_SUPERUSER_EMAIL

# OpenStack vars
unset TEST_IMAGE
unset TEST_FLAVOR

# FCO vars
unset TEST_FCO_URL
unset TEST_FCO_USERNAME
unset TEST_FCO_PASSWORD
unset TEST_FCO_CUSTOMER
unset TEST_FCO_IMAGE_UUID
unset TEST_FCO_VDC_UUID
unset TEST_FCO_NETWORK_UUID
unset TEST_FCO_AGENT_KEY
