# information about the experiment
runexp:
    noise: 1e-5
    numIter: 100
    saveFolder: ./reports/
    confFolder: ./config/
    topologyName: "WordCount"
    conf: wordcount.yaml
    sleep_time: 60
    metricPoll: 1000
    expTime: 300
# information about the parameters
vars:

  - paramname: "component.spout_num"
    node: [storm, storm_nimbus]
    options: [1 3]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: "topology.max.spout.pending"
    node: [storm, storm_nimbus]
    options: [1 2 10 100 1000 10000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: "topology.sleep.spout.wait.strategy.time.ms"
    node: [storm, storm_nimbus]
    options: [1 2 3 10 100]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: "component.split_bolt_num"
    node: [storm, storm_nimbus]
    options: [1 2 3 6]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: "component.count_bolt_num"
    node: [storm, storm_nimbus]
    options: [1 3 6 12]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: "storm.messaging.netty.min_wait_ms"
    node: [storm, storm_nimbus]
    options: [10 100 1000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

  - paramname: tickTime
    node: zookeeper

  - paramname: initLimit
    node: zookeeper

  - paramname: syncLimit
    node: zookeeper
