runexp:
    noise: 1e-5
    numIter: 100
    saveFolder: ./reports/
    confFolder: ./config/
    topologyName: "WordCount"

services:
    deploymentServiceURL: localhost:4984
    continuousIntegrationURL: localhost:4985
    monitoringURL: localhost:4986

var1:
    paramname: "component.spout_num"
    node: [storm, storm_nimbus]
    options: [1 3]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

var4:
    paramname: "comp.test.delay"
    node: [a, b]
    options: [3.4 5e1 34]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 0

var3:
    paramname: "topology.sleep.spout.wait.strategy.time.ms"
    node: [storm, storm_nimbus]
    options: [1 2 3 10 100]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1

var2:
    paramname: "topology.max.spout.pending"
    node: [storm, storm_nimbus]
    options: [1 2 10 100 1000 10000]
    lowerbound: 0
    upperbound: 0
    integer: 0
    categorical: 1
