# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cfy_wrapper.Blueprint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
