# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0006_auto_20160323_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='blueprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfy_wrapper.Blueprint'),
        ),
    ]
