# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0008_auto_20160324_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
