# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0009_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='state',
            field=models.IntegerField(choices=[(-1, b'error'), (0, b'undeployed'), (1, b'pending'), (2, b'uploaded'), (3, b'ready_to_deploy'), (4, b'preparing_deploy'), (5, b'working'), (6, b'deployed'), (101, b'uninstalling'), (102, b'deleting_deployment'), (103, b'deleting_blueprint')], default=1),
        ),
    ]
