# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0010_auto_20160421_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(-1, b'error'), (0, b'undeployed'), (1, b'pending'), (2, b'uploaded'), (3, b'ready_to_deploy'), (4, b'preparing_deploy'), (5, b'working'), (6, b'deployed'), (101, b'uninstalling'), (102, b'deleting_deployment'), (103, b'deleting_blueprint')], help_text=b'What state this error occured in')),
                ('message', models.TextField()),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfy_wrapper.Blueprint')),
            ],
        ),
    ]
