# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0011_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 21, 7, 37, 39, 222942)),
            preserve_default=False,
        ),
    ]
