# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfy_wrapper', '0012_error_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='value',
            field=models.TextField(),
        ),
    ]
